USE [master]
GO

-- ajo onnistuu luonnollisesti vain tunnuksella jolla on oikeus luoda tietokantoja
-- kierretään asia nyt sillä, että koko roska on tämän olemassaolo-iffin sisällä

IF NOT EXISTS (select * from sys.databases where name='VIPUNEN_SA') BEGIN

CREATE DATABASE [VIPUNEN_SA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VIPUNEN_SA', FILENAME = N'E:\MSSQL13.MSSQLSERVER\MSSQL\Data\VIPUNEN_SA.mdf' , SIZE = 204800KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VIPUNEN_SA_log', FILENAME = N'G:\MSSQL13.MSSQLSERVER\MSSQL\DataLog\VIPUNEN_SA_log.ldf' , SIZE = 925696KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
;--GO
ALTER DATABASE [VIPUNEN_SA] SET COMPATIBILITY_LEVEL = 130
;--GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VIPUNEN_SA].[dbo].[sp_fulltext_database] @action = 'enable'
end
;--GO
--END

ALTER DATABASE [VIPUNEN_SA] SET ANSI_NULL_DEFAULT OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET ANSI_NULLS OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET ANSI_PADDING OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET ANSI_WARNINGS OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET ARITHABORT OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET AUTO_CLOSE OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET AUTO_SHRINK OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET AUTO_UPDATE_STATISTICS ON 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET CURSOR_CLOSE_ON_COMMIT OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET CURSOR_DEFAULT  GLOBAL 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET CONCAT_NULL_YIELDS_NULL OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET NUMERIC_ROUNDABORT OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET QUOTED_IDENTIFIER OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET RECURSIVE_TRIGGERS OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET  DISABLE_BROKER 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET DATE_CORRELATION_OPTIMIZATION OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET TRUSTWORTHY OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET PARAMETERIZATION SIMPLE 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET READ_COMMITTED_SNAPSHOT OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET HONOR_BROKER_PRIORITY OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET RECOVERY SIMPLE 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET  MULTI_USER 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET PAGE_VERIFY CHECKSUM  
;--GO
ALTER DATABASE [VIPUNEN_SA] SET DB_CHAINING OFF 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
;--GO
ALTER DATABASE [VIPUNEN_SA] SET DELAYED_DURABILITY = DISABLED 
;--GO
EXEC sys.sp_db_vardecimal_storage_format N'VIPUNEN_SA', N'ON'
;--GO
ALTER DATABASE [VIPUNEN_SA] SET QUERY_STORE = OFF
;--GO

USE [VIPUNEN_SA]
;--GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
;--GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
;--GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
;--GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
;--GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
;--GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
;--GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
;--GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
;--GO
--END

USE [master]
;--GO
ALTER DATABASE [VIPUNEN_SA] SET  READ_WRITE 
;--GO
END
